name: Test Direct File Deployment

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "=== BUILT INDEX.HTML ==="
          cat dist/index.html
          echo -e "\n=== CHECKING SCRIPT TAG ==="
          grep "script" dist/index.html
        
      - name: Deploy to gh-pages branch
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # List what we're about to deploy
          echo "=== FILES TO DEPLOY (from dist) ==="
          ls -la dist/
          echo "=== DIST INDEX.HTML ==="
          cat dist/index.html
          
          # Create a completely new orphan branch
          git checkout --orphan gh-pages-final
          
          # Remove all files from git index
          git rm -rf . || true
          
          # Copy built files directly from dist
          cp dist/index.html .
          cp -r dist/assets .
          
          # Verify what we have
          echo "=== FINAL DEPLOYED FILES ==="
          ls -la
          echo "=== FINAL INDEX.HTML ==="
          cat index.html
          
          # Add and commit
          git add .
          git commit -m "Deploy built files $(date)"
          
          # Force push to gh-pages
          git push -f origin gh-pages-final:gh-pages